#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

container_version() {
 echo "act_runner version v0.2.11" | sed -E 's/.*v([0-9]+\.[0-9]+\.[0-9]+).*/\1/' 
}

container_entrypoint() {
  act_runner register --no-interactive \
   --instance $ACTRUNNER_INSTANCE \
   --token $ACTRUNNER_TOKEN \
   --labels $ACTRUNNER_LABELS
  
  ~/run.sh
}

remove() {
    # ./config.sh remove --unattended --token "${RUNNER_TOKEN}"
    act_runner remove --unattended
}

trap 'remove; exit 130' INT
trap 'remove; exit 143' TERM
